name: Development branches

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Expose branch name
        run: echo ${{ github.ref }}

      # Setup JDK and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version-file: .java-version
          cache: maven
          server-id: ossrh
          server-username: OSS_CENTRAL_USERNAME # env variable for Maven Central
          server-password: OSS_CENTRAL_PASSWORD # env variable for Maven Central

      # Prepare
      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4 -ntp

      # itest
      - name: Run itest
        run: ./mvnw integration-test failsafe:verify -Pitest -U -B -T4 -ntp

      - name: Upload coverage to Codecov
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v5.0.7
        with:
          token: ${{secrets.CODECOV_TOKEN}}
